CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    sex VARCHAR(255) NOT NULL,
    featured INT NOT NULL,
    price FLOAT NOT NULL
);